spring:
  profiles:
    active: test
---
spring:
  profiles: test
  application:
    name: springcloud-config-test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/
server:
  port: 8889
---
spring:
  profiles: dev
  application:
    name: springcloud-config-dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/, http://localhost:8762/eureka/
server:
  port: 8888